### ISSUE TITLE
Multi-domain with Clerk

### ISSUE THREAD

**Issue by vasco3** [get-convex/turbo-expo-nextjs-clerk-convex-monorepo#2]
I have a mono-repo where I have two apps hosted in different domain each. 

for example:
app 1 = bz.com
app 2 = fx.com

That means that `CLERK_JWT_ISSUER_DOMAIN` will not work for both, right? Would I have to remove the `ConvexProviderWithClerk` from the Provider in react?

**Comment by ianmacartney** [comment]
Each app can have their own credentials, and you can have an array of providers in auth.config.js
Does that answer your question @vasco3 ?

**Comment by ianmacartney** [comment]
You can then have multiple environment variables (or hard code multiple values if you don't care about separate dev/prod values)

**Comment by vasco3** [comment]
> Each app can have their own credentials, and you can have an array of providers in auth.config.js Does that answer your question @vasco3 ?

@ianmacartney yes that is what I needed, thanks!
